/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:4a6ee783-2ced-4592-8253-7c310992840e",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_fmkH3Coyl",
    "aws_user_pools_web_client_id": "224sun4lq2m82e6lmq5lr6p6jt",
    "oauth": {}
};


export default awsmobile;
